services:
  postgres:
    image: postgres:16.0-alpine
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - auth
    ports:
      - "5437:5432"
    volumes:
      - ./data/dev/pg-data:/var/lib/postgresql/data

networks:
  auth:
    driver: bridge